env:
  name: saclstm_au.envs.au_replay_env_v9:AUPreOffEnvV9Replay
  kwargs:
    data_root: "G:\\My Drive\\race_out\\val"
    file_glob: "**/*.parquet"
    n_runners: 12
    tick: 0.01
    commission: 0.05
    per_market_loss_cap_bps: 150.0
    reject_unaffordable: true
    forward_fill: true
    tto_max_seconds: 900
    rng_seed: 123
